model:
  name: 'crossattention'
  pretrained: False

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501', 'dukemtmcreid']
  height: 256
  width: 128
  combineall: False
#  transforms: ['random_flip', 'color_jitter']
  save_dir: 'log/crossattention_ain_x1_0_market1501_softmax_cosinelr'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'radam'
  lr: 0.0015
  max_epoch: 250
  batch_size: 64
  fixbase_epoch: 10
  lr_scheduler: 'cosine'
  open_layers: ['sm_mlp_head','lg_mlp_head']

test:
  batch_size: 300
  dist_metric: 'cosine'
  normalize_feature: False
  evaluate: False
  eval_freq: -1
  rerank: False