model:
  name: 'swin'
  pretrained: True

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501', 'market1501']
  height: 224
  width: 224
  combineall: False
  #transforms: ['random_flip', 'color_jitter']
  save_dir: 'log/swin_pvt_softmax_cosinelr'

loss:
  name: 'softmax'
#  softmax:
#    label_smooth: False

train:
  optim: 'adam'
  optim_center: 'adam'
  lr: 0.00015
  max_epoch: 1
  batch_size: 128
  fixbase_epoch: 1
  lr_scheduler: 'cosine'
  open_layers: ['head']

test:
  batch_size: 128
  dist_metric: 'cosine'
  normalize_feature: False
  evaluate: False
  eval_freq: -1
  rerank: False